### ISSUE TITLE
Mini cart does not update language on active language switch

### ISSUE THREAD

**Issue by johnclause** [qTranslate-Team/woocommerce-qtranslate-x#27]
Explanation is here: https://qtranslatexteam.wordpress.com/woocommerce-qtranslate-x-faq/#MiniCartCached

Some solution is described here:
https://wordpress.org/support/topic/minicart-doesnt-change-language-on-lang-switch?replies=10#post-8357061

**Comment by johnclause** [comment]
This should be resolved in the latest code here.

**Comment by Naransim** [comment]
I'm still having this issue, I'm using storefront theme and I'm not a code expert so trying to fix this is very hard. WP version: 4.5.3 | qtranlate-x Version: 3.4.6.8 | Woocommerce & qtranslate-x Version: 1.4

Thanks

![screen shot 2016-08-08 at 10 05 08 am](https://cloud.githubusercontent.com/assets/2684563/17484475/a293c2fe-5d4f-11e6-9ce8-8cdf0e9dc400.png)

**Comment by johnclause** [comment]
I am not sure how to reproduce, but it looks like you miss closing tags [:] in there. Why? Which page did you enter [:en]Black[:ja]... on? Try to re-save those entries.

**Comment by Naransim** [comment]
Hello johnclause, thanks for the reply. Because of it i realized that I was creating the variations in a wrong way, everything is working fine now. Thanks

**Comment by Valixon** [comment]
> Explanation is here: https://qtranslatexteam.wordpress.com/woocommerce-qtranslate-x-faq/#MiniCartCached
> 
> Some solution is described here:
> https://wordpress.org/support/topic/minicart-doesnt-change-language-on-lang-switch?replies=10#post-8357061

This code add to header.php in theme folder
or widget add php code
```
 <?php $url= 'wc_fragments_' . md5( get_current_blog_id() . '_' . get_site_url( get_current_blog_id(), '/' ) . get_template() ) ; ?>
    <script  type="text/javascript">
        localStorage.removeItem('<?php echo $url;?>');
        sessionStorage.removeItem('<?php echo $url;?>');
    </script>
```
